import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Event page",
  description: "Generated by create next app",
};

export default function EventLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="flex w-full p-4">{children}</div>;
}
