import {
  Cog,
  Home,
  Users,
  Archive,
  PieChart,
  LineChart,
  CircleHelp,
  CalendarDays,
} from "lucide-react";

export const citiesInTunisia = [
  "Tunis",
  "Sfax",
  "Sousse",
  "Midoun",
  "Kairouan",
  "Bizerte",
  "Gabès",
  "Ariana",
  "Gafsa",
  "El Mourouj",
  "La Soukra",
  "Ben Arous",
  "Monastir",
  "La Marsa",
  "Hammamet",
  "Tataouine",
  "Douane",
  "Beja",
  "Nabeul",
  "Jendouba",
  "Zarzis",
  "Metlaoui",
  "Béja",
  "Menzel Bourguiba",
  "Mahdia",
  "Sidi Bouzid",
  "Siliana",
  "Mateur",
  "Kasserine",
  "Gremda",
  "Medenine",
  "Douz",
  "Kélibia",
  "Mégrine",
  "Sfax Ouest",
  "Sidi Hassine",
  "Manouba",
  "Tozeur",
  "Beni Khiar",
  "Jemmal",
  "Grombalia",
  "La Goulette",
  "Ksibet Thrayet",
  "M'saken",
  "Menzel Jemil",
  "Takelsa",
  "Soliman",
  "Chebba",
  "Ras Jebel",
  "Sakiet Ezzit",
  "Hammam Sousse",
  "Bou Mhel el-Bassatine",
  "Kébili",
  "El Hamma",
  "Ksar Hellal",
  "Zarzouna",
  "Hergla",
  "Ezzahra",
  "El Kef",
  "Téboursouk",
  "Carthage",
  "Sidi Bou Ali",
  "El Jem",
  "Akouda",
  "Korbous",
  "Menzel Temime",
  "Aïn Beïda",
  "Mareth",
  "Menzel Abderrahmane",
  "Béni Khalled",
  "Borj El Amri",
  "Ghar al Milh",
  "Bou Salem",
  "Skhira",
  "Djebeniana",
  "El Aroussa",
  "Djerba - Houmt Souk",
];

export const navbarLinks = [
  {
    label: "Home",
    route: "/",
    icon: <Home />,
  },
  {
    label: "Dashboard",
    route: "/dashboard",
    icon: <LineChart />,
  },
  {
    label: "Event",
    route: "/event",
    icon: <CalendarDays />,
  },
  {
    label: "Attendees",
    route: "/attendees",
    icon: <Users />,
  },
  {
    label: "Analytics",
    route: "/analytics",
    icon: <PieChart />,
  },
  {
    label: "Settings",
    route: "/settings",
    icon: <Cog />,
  },
  {
    label: "Help",
    route: "/help",
    icon: <CircleHelp />,
  },
  {
    label: "Archive",
    route: "/archive",
    icon: <Archive />,
  },
];
